import {Translation} from "primeng/api";

export const SPANISH_DATE_PICKER: Translation = {
  dayNames: ["Domingo","Lunes","Martes","Miércoles","Jueves","Viernes","Sábado"],
  dayNamesShort: ["Dom","Lun","Mar","Mié","Jue","Vie","Sáb"],
  dayNamesMin: ["D","L","M","X","J","V","S"],
  monthNames: [
    "Enero","Febrero","Marzo","Abril","Mayo","Junio",
    "Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"
  ],
  monthNamesShort: [
    "Ene","Feb","Mar","Abr","May","Jun",
    "Jul","Ago","Sep","Oct","Nov","Dic"
  ],
  today: "Hoy",
  clear: "Limpiar",
  firstDayOfWeek: 1,
  accept: "Aceptar",
  reject: "Rechazar",
  choose: "Elegir",
  upload: "Subir",
  cancel: "Cancelar",
  apply: "Aplicar",
  matchAll: "Coincidir todo",
  matchAny: "Coincidir cualquiera",
  addRule: "Agregar regla",
  removeRule: "Quitar regla",
  startsWith: "Empieza con",
  contains: "Contiene",
  notContains: "No contiene",
  endsWith: "Termina con",
  equals: "Igual a",
  notEquals: "Diferente de",
  noFilter: "Sin filtro",
  lt: "Menor que",
  lte: "Menor o igual que",
  gt: "Mayor que",
  gte: "Mayor o igual que",
  dateIs: "Fecha igual a",
  dateIsNot: "Fecha diferente de",
  dateBefore: "Fecha antes de",
  dateAfter: "Fecha despues de",
  emptyMessage: "No se encontraron resultados",
  emptyFilterMessage: "No se encontraron resultados",
  emptySearchMessage: "No se encontraron resultados",
  searchMessage: "Resultados disponibles",
  selectionMessage: "elementos seleccionados",
  aria: {
    trueLabel: "Verdadero",
    falseLabel: "Falso",
    nullLabel: "No seleccionado",
    star: "1 estrella",
    stars: "{star} estrellas",
    selectAll: "Seleccionar todo",
    unselectAll: "Deseleccionar todo",
    close: "Cerrar",
    previous: "Anterior",
    next: "Siguiente",
    navigation: "Navegacion",
    scrollTop: "Ir arriba",
    moveTop: "Mover arriba",
    moveUp: "Mover hacia arriba",
    moveDown: "Mover hacia abajo",
    moveBottom: "Mover abajo",
    moveToTarget: "Mover al destino",
    moveToSource: "Mover al origen",
    moveAllToTarget: "Mover todo al destino",
    moveAllToSource: "Mover todo al origen",
    pageLabel: "Pagina {page}",
    firstPageLabel: "Primera pagina",
    lastPageLabel: "Ultima pagina",
    nextPageLabel: "Pagina siguiente",
    previousPageLabel: "Pagina anterior",
    rowsPerPageLabel: "Filas por pagina",
    jumpToPageDropdownLabel: "Ir a pagina",
    jumpToPageInputLabel: "Ir a pagina",
    selectRow: "Seleccionar fila",
    unselectRow: "Deseleccionar fila",
    expandRow: "Expandir fila",
    collapseRow: "Contraer fila",
    showFilterMenu: "Mostrar menu de filtro",
    hideFilterMenu: "Ocultar menu de filtro",
    filterOperator: "Operador de filtro",
    filterConstraint: "Restriccion de filtro",
    editRow: "Editar fila",
    saveEdit: "Guardar edicion",
    cancelEdit: "Cancelar edicion",
    listView: "Vista de lista",
    gridView: "Vista de cuadricula",
    slide: "Diapositiva",
    slideNumber: "{slideNumber}",
    zoomImage: "Ampliar imagen",
    zoomIn: "Acercar",
    zoomOut: "Alejar",
    rotateRight: "Rotar a la derecha",
    rotateLeft: "Rotar a la izquierda"
  }
};
